In [10]:
from joblib import dump, load
import numpy as np
model = load('HousePricePrediction.joblib')

In [11]:
features=[[-0.88687591, -0.06919044, -0.07382065,  0.60190594,
       -0.42020574, -0.50925825, -0.59999627, -1.48951473, -1.15811969,
       -0.29165658,  0.85461131]]
model.predict(features)

array([162727.4572])

In [12]:

MSSubClass = 60
MSZoning = 3
LotArea = 8100
LotConfig = 4
BldgType=0
OverallCond = 5
YearBuilt = 2003
YearRemodAdd = 2007
Exterior1st = 11
BsmtFinSF2=0
TotalBsmtSF = 900

In [13]:
features=[[MSSubClass, MSZoning, LotArea, LotConfig, BldgType, OverallCond, YearBuilt, YearRemodAdd, Exterior1st, BsmtFinSF2, TotalBsmtSF]]
model.predict(features)

array([579261.9])

In [14]:
features=[[ 60, 6, 3,  20050,4, 0, 5, 2005, 2003,
       12,  0]]
model.predict(features)

array([238004.3014])